# config file version
apiVersion: 1

deleteDatasources:
  - name: loki
  - name: jaeger

datasources:
- name: loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  jsonData:
    derivedFields:
    - datasourceUid: tempo
      matcherRegex: traceID=(\w+)
      name: TraceID
      url: $${__value.raw}
- name: tempo
  type: tempo
  uid: tempo
  access: 'browser'
  url: http://tempo-query:16686
  isDefault: false
  version: 1
  editable: false
  basicAuth: false